[versions]
ktor = "3.3.3"
komponenter = "1.0.470"
junit = "6.0.1"
testcontainers = "2.0.2"

[libraries]
ktorServerContentNegotation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktorServerNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerAuth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktorServerAuthJwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktorServerTestHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktorSerializationJackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktorServerCallLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktorServerCallLoggingJvm = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktorServerDoubleReceive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor" }
ktorServerCors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktorServerCallId = { module = "io.ktor:ktor-server-call-id", version.ref = "ktor" }
ktorServerMetricsMicrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }

json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version = "1.0.470" }

behandlingsflytKontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version = "0.0.511" }
postmottakKontrakt = { module = "no.nav.aap.postmottak:kontrakt", version = "6.0.3" }

ktorOpenApiGenerator = { module = "no.nav:ktor-openapi-generator", version = "1.0.133" }

logbackClassic = { module = "ch.qos.logback:logback-classic", version = "1.5.22" }
logstashLogbackEncoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "9.0" }

micrometerRegistryPrometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.16.1" }
jacksonDatatypeJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version = "2.20.1" }
jedis = { module = "redis.clients:jedis", version = "7.2.0" }
mockOauth2Server = { module = "no.nav.security:mock-oauth2-server", version = "3.0.1" }
testcontainersRedis = { module = "com.redis:testcontainers-redis", version = "2.2.4" }

joseJwt = { module = "com.nimbusds:nimbus-jose-jwt", version = "10.6" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
assertJ = { module = "org.assertj:assertj-core", version = "3.27.6" }

[bundles]
junit = ["junitJupiterApi", "junitJupiterEngine", "junitJupiterParams", "assertJ"]

[plugins]
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }